In [16]:
# Import Dependencies
import numpy as np
import pandas as pd
import os

## Import and Check Chicago Crime Datasets

In [17]:
# Import 2016 crime data
crime_2016 = os.path.join("Resources", "crime_clean_2016.csv") 

crime_2016_df_final = pd.read_csv(crime_2016, index_col='id')

crime_2016_df_final.head()

,date,day,month,year,time,hour,month_day,day_of_week,district,block,...,location_description,x_coordinate,y_coordinate,iucr,fbi_code,primary_type,domestic,latitude,longitude,arrest
id,,,,,,,,,,,,,,,,,,,,,
10819224,2016-12-31T23:59:00.000,31,12,2016,23:59:00.000,23,1231,5,16,100XX W OHARE ST,...,AIRPORT BUILDING NON-TERMINAL - SECURE AREA,1100658,1934241,0810,06,THEFT,False,41.976290,-87.905227,False
10801137,2016-12-31T23:58:00.000,31,12,2016,23:58:00.000,23,1231,5,5,0000X W 113TH PL,...,RESIDENCE,1178014,1829709,0430,04B,BATTERY,False,41.688033,-87.623931,False
10801110,2016-12-31T23:55:00.000,31,12,2016,23:55:00.000,23,1231,5,19,030XX N LINCOLN AVE,...,RESIDENCE,1166154,1920300,2250,22,LIQUOR LAW VIOLATION,False,41.936885,-87.664770,True
10802006,2016-12-31T23:55:00.000,31,12,2016,23:55:00.000,23,1231,5,1,0000X E WACKER PL,...,HOTEL/MOTEL,1176964,1902140,0486,08B,BATTERY,True,41.886815,-87.625593,False
10801865,2016-12-31T23:54:00.000,31,12,2016,23:54:00.000,23,1231,5,6,078XX S INDIANA AVE,...,RESIDENCE,1178949,1853139,1310,14,CRIMINAL DAMAGE,True,41.752307,-87.619798,False

In [18]:
# Import 2017 crime data
crime_2017 = os.path.join("Resources", "crime_clean_2017.csv") 

crime_2017_df_final = pd.read_csv(crime_2017, index_col='id')

crime_2017_df_final.head()

,date,day,month,year,time,hour,month_day,day_of_week,district,block,...,location_description,x_coordinate,y_coordinate,iucr,fbi_code,primary_type,domestic,latitude,longitude,arrest
id,,,,,,,,,,,,,,,,,,,,,
11192233,2017-12-31T23:58:00.000,31,12,2017,23:58:00.000,23,1231,6,17,046XX N ST LOUIS AVE,...,APARTMENT,1152214,1930694,0630,05,BURGLARY,False,41.965694,-87.715726,False
11196379,2017-12-31T23:50:00.000,31,12,2017,23:50:00.000,23,1231,6,19,024XX N LAKE SHORE DR NB,...,MOVIE HOUSE/THEATER,1175293,1916610,0460,08B,BATTERY,False,41.926559,-87.631294,False
11192540,2017-12-31T23:48:00.000,31,12,2017,23:48:00.000,23,1231,6,18,001XX E SUPERIOR ST,...,HOTEL/MOTEL,1177508,1905401,0890,06,THEFT,False,41.895751,-87.623496,False
11192254,2017-12-31T23:45:00.000,31,12,2017,23:45:00.000,23,1231,6,5,115XX S STATE ST,...,RESIDENCE,1178329,1828012,041A,04B,BATTERY,True,41.683369,-87.622830,False
11192239,2017-12-31T23:45:00.000,31,12,2017,23:45:00.000,23,1231,6,12,019XX S CANAL ST,...,STREET,1173432,1891037,1320,14,CRIMINAL DAMAGE,True,41.856427,-87.638893,False

In [19]:
# Import 2018 crime data
crime_2018 = os.path.join("Resources", "crime_clean_2018.csv") 

crime_2018_df_final = pd.read_csv(crime_2018, index_col='id')

crime_2018_df_final.head()

,date,day,month,year,time,hour,month_day,day_of_week,district,block,...,location_description,x_coordinate,y_coordinate,iucr,fbi_code,primary_type,domestic,latitude,longitude,arrest
id,,,,,,,,,,,,,,,,,,,,,
11556487,2018-12-31T23:59:00.000,31,12,2018,23:59:00.000,23,1231,0,22,112XX S SACRAMENTO AVE,...,STREET,1158309,1829936,1320,14,CRIMINAL DAMAGE,False,41.689079,-87.696064,False
11552699,2018-12-31T23:57:00.000,31,12,2018,23:57:00.000,23,1231,0,6,084XX S SANGAMON ST,...,APARTMENT,1171454,1848783,1310,14,CRIMINAL DAMAGE,False,41.740521,-87.647391,False
11552724,2018-12-31T23:56:00.000,31,12,2018,23:56:00.000,23,1231,0,12,018XX S ALLPORT ST,...,OTHER,1168327,1891230,0440,08B,BATTERY,False,41.857068,-87.657625,True
11552731,2018-12-31T23:55:00.000,31,12,2018,23:55:00.000,23,1231,0,6,078XX S SANGAMON ST,...,APARTMENT,1171332,1852934,0486,08B,BATTERY,False,41.751914,-87.647717,False
11552715,2018-12-31T23:49:00.000,31,12,2018,23:49:00.000,23,1231,0,15,052XX W GLADYS AVE,...,STREET,1140262,1897810,041A,04B,BATTERY,False,41.875684,-87.760479,False

In [20]:
# Check if columns in dataframes are identical 
if crime_2016_df_final.columns.all() == crime_2017_df_final.columns.all() == crime_2018_df_final.columns.all():
    print("Columns are identical")
else:
    print("Columns are not identical")

Columns are identical

In [21]:
# Join datasets for 2016, 2017, and 2018
join1 = crime_2016_df_final.append(crime_2017_df_final)
training_df = join1.append(crime_2018_df_final)
training_df

,date,day,month,year,time,hour,month_day,day_of_week,district,block,...,location_description,x_coordinate,y_coordinate,iucr,fbi_code,primary_type,domestic,latitude,longitude,arrest
id,,,,,,,,,,,,,,,,,,,,,
10819224,2016-12-31T23:59:00.000,31,12,2016,23:59:00.000,23,1231,5,16,100XX W OHARE ST,...,AIRPORT BUILDING NON-TERMINAL - SECURE AREA,1100658,1934241,0810,06,THEFT,False,41.976290,-87.905227,False
10801137,2016-12-31T23:58:00.000,31,12,2016,23:58:00.000,23,1231,5,5,0000X W 113TH PL,...,RESIDENCE,1178014,1829709,0430,04B,BATTERY,False,41.688033,-87.623931,False
10801110,2016-12-31T23:55:00.000,31,12,2016,23:55:00.000,23,1231,5,19,030XX N LINCOLN AVE,...,RESIDENCE,1166154,1920300,2250,22,LIQUOR LAW VIOLATION,False,41.936885,-87.664770,True
10802006,2016-12-31T23:55:00.000,31,12,2016,23:55:00.000,23,1231,5,1,0000X E WACKER PL,...,HOTEL/MOTEL,1176964,1902140,0486,08B,BATTERY,True,41.886815,-87.625593,False
10801865,2016-12-31T23:54:00.000,31,12,2016,23:54:00.000,23,1231,5,6,078XX S INDIANA AVE,...,RESIDENCE,1178949,1853139,1310,14,CRIMINAL DAMAGE,True,41.752307,-87.619798,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11459757,2018-01-01T00:00:00.000,1,1,2018,00:00:00.000,0,102,0,9,045XX S MARSHFIELD AVE,...,RESIDENCE,1166099,1874550,1752,20,OFFENSE INVOLVING CHILDREN,False,41.811344,-87.666279,False
11315895,2018-01-01T00:00:00.000,1,1,2018,00:00:00.000,0,102,0,7,062XX S LAFLIN ST,...,RESIDENCE,1167400,1863456,1153,11,DECEPTIVE PRACTICE,False,41.780873,-87.661825,False
11196173,2018-01-01T00:00:00.000,1,1,2018,00:00:00.000,0,102,0,8,075XX S ST LOUIS AVE,...,RESIDENCE,1154348,1854412,1152,11,DECEPTIVE PRACTICE,False,41.756325,-87.709916,False
11533503,2018-01-01T00:00:00.000,1,1,2018,00:00:00.000,0,102,0,5,005XX E 133RD ST,...,RESIDENCE,1182298,1817141,1562,17,SEX OFFENSE,True,41.653447,-87.608635,False
11479066,2018-01-01T00:00:00.000,1,1,2018,00:00:00.000,0,102,0,2,046XX S EVANS AVE,...,RESIDENCE,1182037,1874422,2826,26,OTHER OFFENSE,False,41.810639,-87.607823,False

In [22]:
# Check sum of lengths of individual datasets match combined length
length1 = len(crime_2016_df_final) + len(crime_2017_df_final) + len(crime_2018_df_final)
if length1 == len(training_df):
    print("Same length")
else: 
    print("Different length")

Same length

In [23]:
# Import 2019 crime data and prepare for testing
crime_2019 = os.path.join("Resources", "crime_clean_2019.csv") 

crime_2019_df_final = pd.read_csv(crime_2019, index_col='id')

crime_2019_df_final.head()

,date,day,month,year,time,hour,month_day,day_of_week,district,block,...,location_description,x_coordinate,y_coordinate,iucr,fbi_code,primary_type,domestic,latitude,longitude,arrest
id,,,,,,,,,,,,,,,,,,,,,
11938228,2019-12-31T23:55:00.000,31,12,2019,23:55:00.000,23,1231,1,7,0000X W 69TH ST,...,STREET,1176896,1859260,143A,15,WEAPONS VIOLATION,False,41.769150,-87.627137,True
11940078,2019-12-31T23:54:00.000,31,12,2019,23:54:00.000,23,1231,1,7,063XX S MAY ST,...,SIDEWALK,1169736,1862855,0420,04B,BATTERY,False,41.779174,-87.653278,False
11938240,2019-12-31T23:48:00.000,31,12,2019,23:48:00.000,23,1231,1,15,004XX S CICERO AVE,...,VEHICLE NON-COMMERCIAL,1144466,1897452,143A,15,WEAPONS VIOLATION,False,41.874624,-87.745053,True
11937967,2019-12-31T23:46:00.000,31,12,2019,23:46:00.000,23,1231,1,11,034XX W JACKSON BLVD,...,STREET,1153587,1898480,143A,15,WEAPONS VIOLATION,False,41.877268,-87.711537,False
11938124,2019-12-31T23:37:00.000,31,12,2019,23:37:00.000,23,1231,1,22,012XX W 99TH ST,...,STREET,1170052,1839142,5112,26,OTHER OFFENSE,False,41.714095,-87.652807,True