In [2]:
# Import Dependencies
import numpy as np
import pandas as pd
import os

# Import 2016-2019 crime data
crime_2016 = os.path.join("..","Resources", "crime_clean_2016.csv") 
crime_2017 = os.path.join("..","Resources", "crime_clean_2017.csv")
crime_2018 = os.path.join("..","Resources", "crime_clean_2018.csv")
crime_2019 = os.path.join("..","Resources", "crime_clean_2019.csv")

crime_2016_df_final = pd.read_csv(crime_2016)
crime_2017_df_final = pd.read_csv(crime_2017)
crime_2018_df_final = pd.read_csv(crime_2018)
crime_2019_df_final = pd.read_csv(crime_2019)

# Join datasets for 2016, 2017, 2018 and 2019 for the analysis
join1 = crime_2016_df_final.append(crime_2017_df_final)
join2 = join1.append(crime_2018_df_final)
crime_data = join2.append(crime_2019_df_final)

In [3]:
arrests = crime_data[['primary_type','arrest']]
arrests['count'] = 1

C:\Users\evans\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [4]:
arrest_count = arrests.groupby(['primary_type','arrest']).agg({'count': 'sum'})

In [6]:
arrest_count

                           count
primary_type      arrest
ARSON             False     1526
                  True       171
ASSAULT           False    64539
                  True     13988
BATTERY           False   156735
...                          ...
STALKING          True        96
THEFT             False   223674
                  True     25232
WEAPONS VIOLATION False     5663
                  True     14131

[65 rows x 1 columns]

In [7]:
# reference: https://stackoverflow.com/questions/23377108/pandas-percentage-of-total-with-groupby
arrest_pct = arrest_count.groupby(level=0).apply(lambda x:100 * x / float(x.sum()))

In [8]:
arrest_pct= arrest_pct.reset_index()

In [9]:
arrest_pct.dtypes

primary_type     object
arrest             bool
count           float64
dtype: object

In [14]:
solved = arrest_pct[arrest_pct['arrest']==True].sort_values("count",ascending=False)

In [15]:
solved

                         primary_type  arrest       count
52                   PUBLIC INDECENCY    True  100.000000
20                           GAMBLING    True  100.000000
51                       PROSTITUTION    True  100.000000
36                          NARCOTICS    True   99.955322
32               LIQUOR LAW VIOLATION    True   99.889989
9   CONCEALED CARRY LICENSE VIOLATION    True   97.002141
26   INTERFERENCE WITH PUBLIC OFFICER    True   95.458299
44                          OBSCENITY    True   78.358209
64                  WEAPONS VIOLATION    True   71.390320
54             PUBLIC PEACE VIOLATION    True   67.447346
48           OTHER NARCOTIC VIOLATION    True   63.636364
17                  CRIMINAL TRESPASS    True   57.244772
38                     NON - CRIMINAL    True   40.000000
42   NON-CRIMINAL (SUBJECT SPECIFIED)    True   33.333333
22                           HOMICIDE    True   30.850647
50                      OTHER OFFENSE    True   21.250278
5                             BATTERY    True   20.675449
3                             ASSAULT    True   17.812982
58                        SEX OFFENSE    True   17.244678
46         OFFENSE INVOLVING CHILDREN    True   13.811966
60                           STALKING    True   12.339332
62                              THEFT    True   10.137160
1                               ARSON    True   10.076606
15            CRIMINAL SEXUAL ASSAULT    True    9.848485
28                       INTIMIDATION    True    9.446254
11                CRIM SEXUAL ASSAULT    True    8.213134
56                            ROBBERY    True    8.115443
34                MOTOR VEHICLE THEFT    True    7.388769
24                  HUMAN TRAFFICKING    True    7.317073
30                         KIDNAPPING    True    6.575342
13                    CRIMINAL DAMAGE    True    5.925906
7                            BURGLARY    True    5.013668
40                       NON-CRIMINAL    True    4.918033
19                 DECEPTIVE PRACTICE    True    4.914884